### ISSUE TITLE
HomeAssistant

### ISSUE THREAD

**Issue by michalzxc** [kpetremann/mqtt-exporter#61]
Hi,
(Me again 😄 )

HomeAssistant can export all sensors to MQTT  by using below (home assistant) configuration:
```
mqtt_statestream:
  base_topic: homeassistant
  publish_attributes: true
  publish_timestamps: true
```
The result seems quite universal:
![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/3be67b30-9d34-48b7-95f0-4367bc336eb8)

![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/2b93f5c7-0a02-4932-9039-91a703163e59)

It lives under:
homeassistant/sensor/NAME, for example homeassistant/sensor/fridge_plug_voltage

![image](https://github.com/kpetremann/mqtt-exporter/assets/1896427/69cd259c-56d9-4e6f-970e-b77938408ac6)
