### ISSUE TITLE
Shelly Plus H&T topic format not working with exporter

### ISSUE THREAD

**Issue by r0ckarong** [kpetremann/mqtt-exporter#62]
I just bought two of these devices and updated them to Firmware 1.0.8 as suggested by the Web UI.
I configured MQTT fine and the messages are showing up in my mosquitto broker instance.

What I can't seem to make work is the other end to write this stuff to my prometheus instance.

For my devices, the shelly topic structure looks like this: 

![Screenshot from 2023-12-07 18-26-38](https://github.com/kpetremann/mqtt-exporter/assets/4920542/7db3f31f-3d5e-4d3b-9716-d80db1d51e17)

For me it is not `<prefix>/<name>/sensor/temperature` it's  `<prefix>/<name>/status/temperature:0`.

I've got another [mqtt exporter tool](https://github.com/dyrkin/tasmota-exporter) working for my tasmota device and it's working fine there. I just don't understand what I'm doing wrong with your tool that it just seems to do nothing.

Here are the relevant snippets of my configs:

docker-compose.yaml
```yaml
[...]
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.48.0
    restart: unless-stopped
    volumes:
      - ./prometheus/:/etc/prometheus/
      # Make sure the folder on the filesystem is owned by 65534:65534
      - ./prometheus/tsdb:/tsdb/
    ports:
      - 9090:9090
    command:
      - '--storage.tsdb.retention.time=2y'
      - '--storage.tsdb.path=/tsdb/'
      - '--web.enable-admin-api'
      - '--config.file=/etc/prometheus/prometheus.yaml'


[...]
  mqtt-exporter:
    image: kpetrem/mqtt-exporter
    container_name: shelly-mqtt-exporter
    ports:
      - 9093:9093
    environment:
      MQTT_ADDRESS: mqtt5
      MQTT_USERNAME: NOOPE
      MQTT_PASSWORD: NOOPE
      MQTT_EXPOSE_CLIENT_ID: true
      MQTT_TOPIC: shellies/+/status/#
      PROMETHEUS_PREFIX: shelly_
      PROMETHEUS_PORT: 9090
    restart: unless-stopped
```

prometheus.yaml
```yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
[...]
  - job_name: "shelly"
    static_configs:
      - targets: ['shelly-mqtt-exporter:9093']
```
